#!/usr/bin/env bash
# Parse a nested markdown checklist (a to-do list) into structured YAML so /ailfred can
# ingest a backlog instead of a one-line objective.
#
# Usage:
#   bash "$CLAUDE_PLUGIN_ROOT/scripts/ailfred-todo-parse.sh" <file|-> [--section "<heading>"] [--pending-only]
#
#   --section        keep only items under a heading whose text contains this string
#                    (case-insensitive substring, e.g. --section "Gabriel")
#   --pending-only   drop items already marked [x]
#
# What it captures, and why each part matters for planning:
#   depth/parent  — the list's own hierarchy: a parent with children is a step
#                   candidate, a leaf is a task candidate
#   checked       — [x] items are already done: never re-planned, only reported
#   line          — the source line number, so completion can be written back to the
#                   very same line later (see ailfred-todo-sync.sh)
#   section       — the nearest heading above the item: unrelated headings are
#                   different goals, not one mega-goal
#   notes         — nested bullets WITHOUT a checkbox belong to the closest item as
#                   context ("- definições de camadas: presentation, infra…"), and
#                   must not become tasks of their own
#
# Fenced code blocks are skipped: a ``` block may contain list-looking lines.
set -euo pipefail

FILE=""
SECTION=""
PENDING_ONLY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --section)      SECTION="${2:-}"; shift 2 ;;
    --pending-only) PENDING_ONLY=1; shift ;;
    -h|--help)      sed -n '2,25p' "$0"; exit 0 ;;
    *)              FILE="$1"; shift ;;
  esac
done

[ -n "$FILE" ] || { echo "ERROR: file required (use - for stdin)" >&2; exit 1; }
if [ "$FILE" = "-" ]; then
  SRC="$(mktemp)"; trap 'rm -f "$SRC"' EXIT; cat > "$SRC"; LABEL="(stdin)"
else
  [ -f "$FILE" ] || { echo "ERROR: file not found: $FILE" >&2; exit 1; }
  SRC="$FILE"; LABEL="$FILE"
fi

awk -v label="$LABEL" -v want_section="$SECTION" -v pending_only="$PENDING_ONLY" '
function yq(s) { gsub(/'\''/, "'\'''\''", s); return "'\''" s "'\''" }   # YAML single-quoted scalar
function lower(s) { return tolower(s) }

BEGIN { n=0; fence=0; section=""; stack_top=-1; total=0; checked_count=0; maxdepth=0 }

# fenced code blocks: ``` or ~~~
/^[[:space:]]*(```|~~~)/ { fence = !fence; next }
fence { next }

# headings define the cluster an item belongs to
/^#{1,6}[[:space:]]+/ {
  section = $0
  sub(/^#+[[:space:]]+/, "", section)
  sub(/[[:space:]]+$/, "", section)
  stack_top = -1          # a heading resets the hierarchy
  next
}

{
  line = $0
  # checklist item?  "- [ ] text" / "* [x] text" / "+ [X] text"
  if (match(line, /^[[:space:]]*[-*+][[:space:]]+\[[ xX]\][[:space:]]*/)) {
    # Capture RSTART/RLENGTH FIRST: every later match() call overwrites them.
    mstart = RSTART; mlen = RLENGTH
    box = substr(line, mstart, mlen)
    text = substr(line, mstart + mlen)
    indent = match(line, /[^[:space:]]/) - 1
    is_checked = (box ~ /\[[xX]\]/) ? 1 : 0

    # depth from an indent stack: tolerates 2-space, 4-space and tab mixes
    while (stack_top >= 0 && indent_at[stack_top] >= indent) stack_top--
    stack_top++
    indent_at[stack_top] = indent
    depth = stack_top

    n++
    id = sprintf("I%02d", n)
    item_id[n]=id; item_line[n]=NR; item_depth[n]=depth; item_checked[n]=is_checked
    item_text[n]=text; item_section[n]=section
    item_parent[n] = (depth > 0 && last_at[depth-1] != "") ? last_at[depth-1] : ""
    if (item_parent[n] != "") has_child[item_parent[n]] = 1
    last_at[depth] = id
    for (d = depth+1; d <= 20; d++) last_at[d] = ""
    cur = n
    if (depth > maxdepth) maxdepth = depth
    total++; if (is_checked) checked_count++
    next
  }

  # plain nested bullet (no checkbox) => note of the current item
  if (cur > 0 && match(line, /^[[:space:]]+[-*+][[:space:]]+/)) {
    note = substr(line, RSTART + RLENGTH)   # no further match() before this line
    sub(/[[:space:]]+$/, "", note)
    if (note != "") { note_count[cur]++; notes[cur, note_count[cur]] = note }
    next
  }
}

END {
  print "# generated by ailfred-todo-parse.sh — do not edit by hand"
  print "source: " yq(label)
  print "summary:"
  print "  items_total: " total
  print "  items_checked: " checked_count
  print "  items_pending: " (total - checked_count)
  print "  max_depth: " maxdepth
  print "items:"
  printed = 0
  for (i = 1; i <= n; i++) {
    if (want_section != "" && index(lower(item_section[i]), lower(want_section)) == 0) continue
    if (pending_only == 1 && item_checked[i] == 1) continue
    printed++
    print "  - id: " item_id[i]
    print "    line: " item_line[i]
    print "    depth: " item_depth[i]
    print "    parent: " (item_parent[i] == "" ? "null" : item_parent[i])
    print "    section: " yq(item_section[i])
    print "    checked: " (item_checked[i] ? "true" : "false")
    print "    has_children: " (has_child[item_id[i]] ? "true" : "false")
    print "    text: " yq(item_text[i])
    if (note_count[i] > 0) {
      print "    notes:"
      for (k = 1; k <= note_count[i]; k++) print "      - " yq(notes[i, k])
    } else {
      print "    notes: []"
    }
  }
  if (printed == 0) print "  []"
  print "# emitted: " printed " item(s)"
}
' "$SRC"
